<?php
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @return array
 * @hook theme_suggestions_HOOK_alter
 */
function timer_autologout_theme(): array {
  return [
    'timer_autoLogout' => [
      'variables' => [
        'remainingTime' => NULL,
        'prefix_text' => NULL,
        'suffix_text' => NULL,
        'modal_timer' => NULL,
      ],
      'template' => 'timer_autoLogout',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * @param array $suggestions
 * @param array $variables
 */
function timer_autologout_theme_suggestions_block_alter(array &$suggestions, array $variables): void {
  if ($block_id = $variables['elements']['#id']) {
    $suggestions[] = 'block__' . $block_id;
  }
}
