timer_auto_logout.settings:
  type: config_object
  label: 'Timer Auto Logout Settings'
  mapping:
    prefix_text:
      type: label
      label: 'Prefix Text'
    suffix_text:
      type: label
      label: 'Suffix Text'
